services:
  my-vdi:
    image: lscr.io/linuxserver/webtop:alpine-xfce
    container_name: my-vdi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - ./init.sh:/custom-cont-init.d/init.sh
    ports:
      - "3000:3000"
      - "3001:3001"
    shm_size: "1gb"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: unless-stopped
